import { ArrowRight, Droplets, HeartPulse, Siren, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorState, EventCard, ImpactCard, LoadingState, NewsCard, ProgramCard, SectionTitle } from "../components/site";
import { usePublicResource } from "../hooks/usePublicResource";
import { getEvents, getNews, getPrograms } from "../services/api";

export function HomePage() {
  const programs = usePublicResource(getPrograms);
  const events = usePublicResource(getEvents);
  const news = usePublicResource(getNews);

  return <>
    <section className="hero-grid border-b border-[var(--border)]"><div className="shell grid gap-12 py-20 md:grid-cols-[1.1fr_.9fr] md:items-center md:py-28"><div><p className="eyebrow">Indian Red Cross Society - NIET</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.055em] text-[var(--dark)] sm:text-6xl">Small acts of care can shape a stronger community.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[var(--grey)]">A student-led initiative at Noida Institute of Engineering & Technology, making space for service, preparedness and practical humanitarian learning.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/donate" className="button button-primary">Donate now <ArrowRight size={16} /></Link><Link to="/membership" className="button button-secondary">Become a volunteer</Link></div><p className="mt-5 text-xs font-semibold text-[var(--grey)]">Official programme, leadership and contact information will be added after confirmation.</p></div><div className="relative overflow-hidden rounded-[2rem] bg-[var(--dark)] p-8 text-white sm:p-12"><div className="absolute right-0 top-0 h-40 w-40 rounded-bl-full bg-[var(--crimson)]" /><HeartPulse className="relative mb-20 text-red-300" size={42} /><p className="relative max-w-xs text-3xl font-semibold leading-tight">Prepared students. Caring communities. Reliable action.</p><div className="relative mt-12 border-t border-white/20 pt-5 text-sm text-slate-300">NIET campus initiative<br />Details to be confirmed</div></div></div></section>
    <section className="shell py-12"><div className="grid grid-cols-2 gap-7 md:grid-cols-4"><ImpactCard value="TBC" label="Lives helped" /><ImpactCard value="TBC" label="Blood units collected" /><ImpactCard value="TBC" label="Camps organized" /><ImpactCard value="TBC" label="Volunteers joined" /></div></section>
    <section className="border-y border-[var(--border)] bg-white"><div className="shell py-16"><SectionTitle eyebrow="Get involved" title="A clear next step for every kind of support." description="Choose the way you want to learn, serve or help make a future activity possible." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><QuickAction icon={<HeartPulse />} title="Donate" text="Support future initiatives." href="/donate" /><QuickAction icon={<Users />} title="Volunteer" text="Bring your time and skills." href="/membership" /><QuickAction icon={<Droplets />} title="Find blood" text="Search interface ready for API." href="/contact#blood" /><QuickAction icon={<Siren />} title="Report emergency" text="Share information responsibly." href="/contact#emergency" /></div></div></section>
    <section className="shell py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionTitle eyebrow="Our focus" title="Programmes built around practical care." description="Explore the initiative's published programme areas." /><Link to="/programs" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--crimson)]">View all programmes <ArrowRight size={16} /></Link></div><div className="mt-10">{programs.loading && <LoadingState />}{!programs.loading && programs.error && <ErrorState onRetry={programs.retry} />}{!programs.loading && !programs.error && programs.data?.length === 0 && <EmptyState message="No published programmes are available at the moment." />}{!programs.loading && !programs.error && programs.data && programs.data.length > 0 && <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{programs.data.slice(0, 3).map((program) => <ProgramCard key={program.id} program={program} />)}</div>}</div></section>
    <section className="bg-[var(--light)]"><div className="shell grid gap-14 py-20 lg:grid-cols-2"><div><SectionTitle eyebrow="On the calendar" title="Latest events" /><div className="mt-8">{events.loading && <LoadingState />}{!events.loading && events.error && <ErrorState onRetry={events.retry} />}{!events.loading && !events.error && events.data?.length === 0 && <EmptyState message="No upcoming events at the moment." />}{!events.loading && !events.error && events.data && events.data.length > 0 && <div className="grid gap-4">{events.data.slice(0, 2).map((event) => <EventCard key={event.id} event={event} />)}</div>}</div><Link to="/events" className="button button-secondary mt-7">See events <ArrowRight size={16} /></Link></div><div><SectionTitle eyebrow="From the initiative" title="Latest news" /><div className="mt-8">{news.loading && <LoadingState />}{!news.loading && news.error && <ErrorState onRetry={news.retry} />}{!news.loading && !news.error && news.data?.length === 0 && <EmptyState message="No published news is available at the moment." />}{!news.loading && !news.error && news.data && news.data.length > 0 && <div className="grid gap-8">{news.data.map((item) => <NewsCard key={item.id} item={item} />)}</div>}</div></div></div></section>
    <section className="shell py-20"><div className="rounded-[2rem] bg-[var(--crimson)] px-7 py-12 text-white sm:px-12"><p className="eyebrow text-red-200">Help build the next chapter</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold leading-tight">Your support gives students room to turn care into action.</h2><Link to="/donate" className="button mt-7 bg-white text-[var(--crimson)]">Donate now <ArrowRight size={16} /></Link></div></section>
  </>;
}

function QuickAction({ icon, title, text, href }: { icon: React.ReactNode; title: string; text: string; href: string }) { return <Link to={href} className="group border border-[var(--border)] bg-[var(--cream)] p-5 hover:border-[var(--crimson)]"><span className="text-[var(--crimson)]">{icon}</span><h3 className="mt-4 font-semibold text-[var(--dark)]">{title}</h3><p className="mt-1 text-sm text-[var(--grey)]">{text}</p><ArrowRight className="mt-5 text-[var(--crimson)] transition group-hover:translate-x-1" size={16} /></Link>; }
